name: pos_sdk
description: A new Flutter package project.
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  esc_pos_printer: ^3.1.6
  esc_pos_blue: 
    git: https://github.com/ayalma/esc_pos_blue.git
  mobile_pos_plugin: 
    path : ../mobile_pos_plugin
  charset_converter: ^1.0.3
  aft_pos_sdk:
    path : ../aft_pos_sdk
  commons:
    path: ../commons


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

